#!/usr/bin/env bash
# Installs RatOS
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

# Add root rights to X11
echo_green "Adding root rights to X11.."
echo needs_root_rights=yes>>/etc/X11/Xwrapper.config

echo_green "Installing KlipperScreen"

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
mkdir KlipperScreen
chown pi:pi KlipperScreen
gitclone KLIPPERSCREEN KlipperScreen
pushd "/home/${BASE_USER}/KlipperScreen" &> /dev/null || exit 1
sudo -u ${BASE_USER} ./scripts/KlipperScreen-install.sh

# Mute output from klipperscreen service
sudo sed -i 's/\[Service\]/\[Service\]\n\StandardOutput=null\nStandardError=null/g' /etc/systemd/system/KlipperScreen.service

popd &> /dev/null || exit 1
popd &> /dev/null || exit 1

sudo systemctl stop KlipperScreen
