#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="x86_64"
BASE_BOARD="armbian_debian_xcfe"
BASE_BOOT_PARTITION=2
BASE_ROOT_PARTITION=3
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_PATH="image"

# Image source
DOWNLOAD_URL_CHECKSUM="https://armbian.lv.auroradev.org/dl/uefi-x86/archive/Armbian_25.8.1_Uefi-x86_trixie_current_6.12.41_xfce_desktop.img.xz.sha"
DOWNLOAD_URL_IMAGE="https://armbian.lv.auroradev.org/dl/uefi-x86/archive/Armbian_25.8.1_Uefi-x86_trixie_current_6.12.41_xfce_desktop.img.xz"

# export Variables
export BASE_ARCH
export BASE_BOARD
export BASE_BOOT_PARTITION
export BASE_ROOT_PARTITION
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_PATH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
